### ISSUE TITLE
ESLint configuration missing

### ISSUE THREAD

**Issue by fpauser** [emberjs/ember-module-unification-blueprint#1]
I tried this blueprint, following https://madhatted.com/2017/5/30/ember-js-module-unification-update-and-contribution-tips but get this error when running the generated app  via `ember s`:

```
File: main.js
The Broccoli Plugin: [broccoli-persistent-filter:EslintValidationFilter] failed with:
Error: No ESLint configuration found.
    at getLocalConfig (/home/fpauser/projects/module-unification-test-app/node_modules/eslint/lib/config.js:162:35)
```

**Comment by rwjblue** [comment]
Good catch! We need to add the file [from here](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/.eslintrc.js) into our `files` directory [here](https://github.com/emberjs/ember-module-unification-blueprint/tree/master/files). Would you happen to have time to PR?

**Comment by fpauser** [comment]
See https://github.com/emberjs/ember-module-unification-blueprint/pull/2
