### ISSUE TITLE
Update to use RFC 176/ES6 Module imports

### ISSUE THREAD

**Issue by chriskrycho** [emberjs/ember-module-unification-blueprint#6]
I believe *none* of the imports here are fully updated for RFC 176 conformance.

See e.g. the [`Application` import](https://github.com/emberjs/ember-module-unification-blueprint/blob/master/files/src/main.js#L6), the [`Router` import](https://github.com/emberjs/ember-module-unification-blueprint/blob/master/files/src/router.js), and (most horrifyingly of all 😱) the old-shims-using [`Component` import](https://github.com/emberjs/ember-module-unification-blueprint/blob/master/files/src/ui/components/my-component/component.js#L1).

**Comment by rwjblue** [comment]
Thanks for reporting!
